Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,42 +1,42 @@
-name: build-images
-on:
-  workflow_call:
-jobs:
-  validate-helm-charts:
-    runs-on: ubuntu-latest
-    outputs:
-      num: ${{ steps.check.outputs.num_dir_changed }}
-      dir: ${{ steps.check.outputs.end_dir }}
-    strategy:
-      fail-fast: false
-      matrix:
-        dir: [backups,images/application,images/dev,images/pipeline]
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 2
-      - name: Check Changes
-        id: "check"
-        run: |
-          changed_files="$(git show --pretty="" --name-only)"
-          echo "$changed_files"
-          dir_changed="$(echo "$changed_files" | xargs dirname | grep -o "${{ matrix.dir }}/[^/]*" | sort | uniq || true)"
-          echo "---------------"
-          echo "$dir_changed"
-          num_dir_changed="$(echo "$dir_changed" | grep -c "${{ matrix.dir }}" || true)"
-          echo "-----------"
-          echo "$num_dir_changed"
-          echo "=============="
-          end_dir="$(echo "$dir_changed" | cut -d'/' -f2)"
-          end_dir="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${end_dir[@]}")"
-          echo "$end_dir"
-          echo "end_dir=$end_dir" >> $GITHUB_OUTPUT
-          echo "num_dir_changed=$num_dir_changed" >> $GITHUB_OUTPUT
-      - if : ${{ steps.check.outputs.num_dir_changed > 0 }}
-        run: |
-          echo "Conditional-------------"
-          echo ${{ steps.check.outputs.end_dir }}
+# name: build-images
+# on:
+#   workflow_call:
+# jobs:
+#   validate-helm-charts:
+#     runs-on: ubuntu-latest
+#     outputs:
+#       num: ${{ steps.check.outputs.num_dir_changed }}
+#       dir: ${{ steps.check.outputs.end_dir }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         dir: [backups,images/application,images/dev,images/pipeline]
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 2
+#       - name: Check Changes
+#         id: "check"
+#         run: |
+#           changed_files="$(git show --pretty="" --name-only)"
+#           echo "$changed_files"
+#           dir_changed="$(echo "$changed_files" | xargs dirname | grep -o "${{ matrix.dir }}/[^/]*" | sort | uniq || true)"
+#           echo "---------------"
+#           echo "$dir_changed"
+#           num_dir_changed="$(echo "$dir_changed" | grep -c "${{ matrix.dir }}" || true)"
+#           echo "-----------"
+#           echo "$num_dir_changed"
+#           echo "=============="
+#           end_dir="$(echo "$dir_changed" | cut -d'/' -f2)"
+#           end_dir="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${end_dir[@]}")"
+#           echo "$end_dir"
+#           echo "end_dir=$end_dir" >> $GITHUB_OUTPUT
+#           echo "num_dir_changed=$num_dir_changed" >> $GITHUB_OUTPUT
+#       - if : ${{ steps.check.outputs.num_dir_changed > 0 }}
+#         run: |
+#           echo "Conditional-------------"
+#           echo ${{ steps.check.outputs.end_dir }}
   
   # build-image:
   #   needs: validate-helm-charts
